
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[197] =
    {   0,
       61,    2,    3,   60,    1,    2,    3,   60,    1,   60,
       12,   60,   11,   12,   60,   13,   60,   12,   60,   12,
       60,   10,   12,   60,    9,   12,   60,   60,   52,   60,
       53,   60,   51,   60,   54,   60,   55,   60,   56,   60,
       57,   60,   58,   60,   59,   60,   17,   60,   18,   60,
       60,   15,   60,   14,   60,   26,   60,   27,   60,   24,
       60,   60,   21,   60,   60,   60,   22,   60,   22,   60,
       60,   25,   60,   60,   60,   19,   60,   39,   60,   38,
       39,   60,   39,   60,   46,   60,   44,   46,   60,   45,
       60,   42,   46,   60,   43,   46,   60,   46,   60,   40,

       46,   60,   40,   46,   60,   46,   60,   35,   60,   36,
       60,   33,   60,   30,   60,   60,   31,   60,   31,   60,
       60,   34,   60,   60,   60,   29,   60,   47,   60,   50,
       60,   49,   60,   60,    1,   11,16392,   10,    9,   52,
       51,   54,   55,   57,   58,   17,   16,   14,   26,   27,
       20,   22,   22,   23,   25,   21,   19,   38,   44,   40,
       40,   41,   35,   31,   31,   32,   34,   30,   29,   48,
        5, 8200,16392,   16,   20,   22,   22,   22,   22,   23,
       23,   37,   40,   40,   40,   40,   41,   31,   31,   31,
       31,   32,    7,    4,    6,   28

    } ;

static yyconst flex_int16_t yy_accept[191] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    5,    9,   11,   13,   16,   18,
       20,   22,   25,   28,   29,   31,   33,   35,   37,   39,
       41,   43,   45,   47,   49,   51,   52,   54,   56,   58,
       60,   62,   63,   65,   66,   67,   69,   71,   72,   74,
       75,   76,   78,   80,   83,   85,   87,   90,   92,   95,
       98,  100,  103,  106,  108,  110,  112,  114,  116,  117,
      119,  121,  122,  124,  125,  126,  128,  130,  132,  134,
      135,  136,  137,  137,  137,  137,  138,  139,  140,  141,

      142,  143,  143,  144,  145,  146,  147,  148,  149,  150,
      151,  152,  152,  152,  152,  153,  153,  153,  154,  154,
      155,  156,  157,  158,  159,  159,  160,  160,  160,  161,
      161,  161,  162,  163,  164,  164,  164,  165,  165,  165,
      166,  167,  168,  169,  170,  171,  172,  172,  172,  172,
      172,  173,  174,  174,  175,  176,  177,  178,  178,  179,
      180,  181,  182,  183,  184,  185,  186,  187,  188,  189,
      190,  191,  192,  193,  193,  194,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  196,  197,  197
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    6,    7,    8,    7,
        7,    7,    7,    9,    7,   10,    7,   11,   12,   13,
       13,   13,   13,   13,   13,   14,   14,   15,   16,   17,
        1,   18,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   25,   26,   25,   25,   25,   27,   28,   29,   25,
       30,   31,   25,   25,   32,   25,   33,   34,   25,   25,
        7,   35,    7,    7,   25,    1,   19,   20,   21,   22,

       23,   24,   25,   25,   26,   25,   25,   25,   27,   28,
       29,   25,   30,   31,   25,   25,   32,   25,   33,   34,
       25,   25,    1,    7,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[36] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    6,    7,    1,    1,    8,    8,
        8,    8,    8,    8,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    1
    } ;

static yyconst flex_int16_t yy_base[228] =
    {   0,
        0,    2,    5,    0,   40,    0,   74,   76,   78,   80,
       83,    0,  118,    0,  152,  153,  156,  170,  185,    0,
      218,  220,  569,  570,  160,  174,  570,  555,  570,  203,
        0,    0,    0,  570,  554,  570,    0,  551,  550,  570,
        0,  546,  570,  545,  570,    0,  570,    0,  542,  225,
      570,    0,  570,  508,  516,  220,  223,  523,    0,  517,
      515,    0,  570,  528,    0,  570,  236,  570,  570,  570,
      494,  230,  235,    0,  523,  570,  570,  570,  489,  245,
      248,    0,    0,  503,  501,    0,  570,  570,  570,    0,
      249,  512,  247,  482,  475,  269,    0,    0,  496,    0,

      495,  487,  476,    0,  465,  457,    0,    0,  451,  271,
        0,  444,  436,  411,  270,  264,    0,  275,    0,    0,
        0,  570,    0,  429,  420,  282,  415,  405,  281,  284,
        0,  286,    0,  410,  396,  391,  290,  293,    0,  295,
        0,    0,  570,    0,  570,  570,  374,  362,  372,  308,
      570,  310,  382,    0,    0,  570,  317,  301,  303,    0,
        0,    0,  570,  570,  314,  305,    0,    0,  570,  313,
      307,    0,    0,  293,  570,  570,  287,  251,  249,  247,
      242,  223,  208,  199,  151,  137,  570,  570,  570,  326,
      335,  344,  353,  362,  371,  373,  382,  387,  392,  401,

      410,  412,  417,  419,  428,  432,  441,  446,  455,  464,
      466,  475,  477,  486,  491,  500,  508,  513,  518,  523,
      527,  532,  537,  541,  546,  550,  559
    } ;

static yyconst flex_int16_t yy_def[228] =
    {   0,
      190,  190,  189,    3,  189,    5,  191,  191,  192,  192,
      189,   11,  189,   13,  193,  193,  194,  194,  189,   19,
      195,  195,  189,  189,  189,  189,  189,  189,  189,  189,
      196,  197,  198,  189,  189,  189,  199,  200,  189,  189,
      201,  189,  189,  189,  189,  202,  189,  203,  189,  189,
      189,  204,  189,  205,  189,  189,  189,  206,  207,  189,
      189,  208,  189,  189,  209,  189,  189,  189,  189,  189,
      210,  189,  189,  211,  189,  189,  189,  189,  212,  189,
      189,  213,  214,  189,  189,  215,  189,  189,  189,  216,
      189,  189,  189,  189,  189,  217,  197,  198,  189,  199,

      200,  200,  189,  201,  189,  189,  218,  203,  189,  189,
      219,  189,  205,  189,  189,  189,  220,  189,  221,  222,
      207,  189,  208,  189,  209,  189,  189,  210,  189,  189,
      223,  189,  224,  189,  189,  212,  189,  189,  225,  189,
      226,  214,  189,  215,  189,  189,  189,  189,  189,  189,
      189,  217,  227,  218,  219,  189,  189,  189,  189,  220,
      221,  222,  189,  189,  189,  189,  223,  224,  189,  189,
      189,  225,  226,  189,  189,  189,  227,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,    0,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189
    } ;

static yyconst flex_int16_t yy_nxt[606] =
    {   0,
      189,   25,   26,   25,   26,   27,   28,   29,   27,   27,
       27,   27,   27,   27,   30,   27,   27,   27,   27,   31,
       32,   27,   27,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   27,
       34,   35,   36,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   34,   39,   40,   39,   40,   42,
       43,   42,   43,   34,   44,   45,   34,   34,   46,   34,
       34,   47,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   34,   34,   49,
       50,   34,   51,   52,   53,   54,   53,   55,   56,   57,
       57,   57,   58,   59,   60,   61,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   34,   64,   64,   65,   65,   67,   68,   69,
       70,   91,   91,   71,   67,  188,   72,   73,   73,   73,
       74,   67,   68,   69,   70,   91,   91,   71,   67,  187,
       72,   73,   73,   73,   74,   34,   75,   76,   34,   77,
       34,   78,   79,   78,   34,   80,   81,   81,   81,   82,

       83,   84,   85,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   34,
       88,   89,   88,   89,   93,   94,  110,  110,   95,  186,
      115,  115,  115,  118,  118,  118,  118,  126,  185,  116,
      129,  129,  129,  184,  126,  132,  132,  132,  132,  130,
       91,   91,   90,  117,   90,  137,  137,  137,  140,  140,
      140,  140,  183,  131,  138,  182,  146,  181,  146,  147,
      150,  151,  110,  110,  159,  159,  146,  180,  139,  146,
      115,  115,  115,  126,  153,  118,  118,  118,  118,  151,
      126,  129,  129,  129,  166,  166,  132,  132,  132,  132,

      137,  137,  137,  171,  171,  140,  140,  140,  140,  150,
      151,  150,  151,  159,  159,  166,  166,  171,  171,  179,
      169,  164,  178,  153,  156,  153,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       96,   96,   97,   97,  151,   97,   97,   97,   97,   97,
       97,   98,  176,  175,   98,   98,  100,  174,  170,  100,

      100,  101,  101,  169,  101,  101,  101,  101,  101,  101,
      104,  134,  165,  104,  104,  104,  104,  104,  104,  107,
      107,  108,  164,  163,  108,  108,  111,  111,  112,  112,
      124,  112,  112,  112,  112,  112,  112,  120,  158,  120,
      120,  121,  121,  157,  121,  121,  121,  121,  121,  121,
      123,  156,  109,  123,  123,  125,  125,  125,  106,  125,
      125,  125,  125,  125,  127,  127,  105,  127,  127,  127,
      127,  127,  127,  133,  133,  135,  135,  103,  135,  135,
      135,  135,  135,  135,  141,  141,  142,  142,  102,  142,
      142,  142,  142,  142,  142,  144,  102,   99,  144,  144,

      145,  145,  149,  145,  145,  145,  145,  145,  145,  152,
      152,  148,  152,   92,  152,  152,  152,  154,  143,  143,
      154,  154,  155,  136,  134,  155,  155,  160,  128,  124,
      160,  161,  122,  122,  161,  161,  162,  119,  114,  162,
      162,  167,  113,  109,  167,  168,  106,  105,  168,  168,
      172,  103,  102,  172,  173,   99,   92,  173,  173,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  189,   23,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189
    } ;

static yyconst flex_int16_t yy_chk[606] =
    {   0,
        0,    1,    1,    2,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    7,    7,    8,    8,    9,
        9,   10,   10,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   15,   16,   15,   16,   17,   17,   17,
       17,   25,   25,   17,   17,  186,   17,   17,   17,   17,
       17,   18,   18,   18,   18,   26,   26,   18,   18,  185,
       18,   18,   18,   18,   18,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       21,   21,   22,   22,   30,   30,   50,   50,   30,  184,
       56,   56,   56,   57,   57,   57,   57,   67,  183,   56,
       72,   72,   72,  182,   67,   73,   73,   73,   73,   72,
       91,   91,   21,   56,   22,   80,   80,   80,   81,   81,
       81,   81,  181,   72,   80,  180,   93,  179,   93,   93,
       96,   96,  110,  110,  116,  116,   93,  178,   80,   93,
      115,  115,  115,  126,   96,  118,  118,  118,  118,  177,
      126,  129,  129,  129,  130,  130,  132,  132,  132,  132,

      137,  137,  137,  138,  138,  140,  140,  140,  140,  150,
      150,  152,  152,  159,  159,  166,  166,  171,  171,  174,
      170,  165,  158,  150,  157,  152,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      196,  196,  197,  197,  153,  197,  197,  197,  197,  197,
      197,  198,  149,  148,  198,  198,  199,  147,  136,  199,

      199,  200,  200,  135,  200,  200,  200,  200,  200,  200,
      201,  134,  128,  201,  201,  201,  201,  201,  201,  202,
      202,  203,  127,  125,  203,  203,  204,  204,  205,  205,
      124,  205,  205,  205,  205,  205,  205,  206,  114,  206,
      206,  207,  207,  113,  207,  207,  207,  207,  207,  207,
      208,  112,  109,  208,  208,  209,  209,  209,  106,  209,
      209,  209,  209,  209,  210,  210,  105,  210,  210,  210,
      210,  210,  210,  211,  211,  212,  212,  103,  212,  212,
      212,  212,  212,  212,  213,  213,  214,  214,  102,  214,
      214,  214,  214,  214,  214,  215,  101,   99,  215,  215,

      216,  216,   95,  216,  216,  216,  216,  216,  216,  217,
      217,   94,  217,   92,  217,  217,  217,  218,   85,   84,
      218,  218,  219,   79,   75,  219,  219,  220,   71,   64,
      220,  221,   61,   60,  221,  221,  222,   58,   55,  222,
      222,  223,   54,   49,  223,  224,   44,   42,  224,  224,
      225,   39,   38,  225,  226,   35,   28,  226,  226,  227,
      227,  227,  227,  227,  227,  227,  227,  227,   23,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "asm.l"
#line 2 "asm.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <assert.h>
	#include "y.tab.h"

	typedef const char *cstr_t;
	cstr_t ids[0x100];
	cstr_t equs[0x100];
	size_t i, line = 1;
	cstr_t id;

	FILE *infs[0x100];
	cstr_t incs[0x100];
	size_t inls[0x100];
	cstr_t inns[0x100];
	size_t f_i, i_i, l_i, n_i;
	cstr_t cfn;

	void insert(cstr_t, cstr_t);
	cstr_t get(cstr_t);

	cstr_t substitute(cstr_t);
	int evalnum(cstr_t);

	void loadfile(cstr_t);
	void doabort(void);

	char *lowerdup(cstr_t);

	void yyerror(cstr_t s) { }

	#define MXT_TOLOWER(c) (((c)>='A'&&(c)<='Z')?((c)+'a'-'A'):(c))










#line 741 "lex.yy.c"

#define INITIAL 0
#define CONTENT 1
#define EQU 2
#define EQU_REST 3
#define EQU_END 4
#define MACRO 5
#define MACRO_BODY 6
#define INC 7
#define DB 8
#define EXPR 9
#define STR 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 99 "asm.l"


#line 941 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 190 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 570 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 102 "asm.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 103 "asm.l"
{ yyless(0); BEGIN CONTENT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 104 "asm.l"
{ fprintf(stderr, "WFT\n"); doabort(); }
	YY_BREAK


case 4:
YY_RULE_SETUP
#line 108 "asm.l"
{ BEGIN INC; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 109 "asm.l"
{ BEGIN DB; yylval.i = MXT_TOLOWER(yytext[2]); return T_DB; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 110 "asm.l"
{ BEGIN MACRO; return T_DEFMACRO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 111 "asm.l"
{ BEGIN EQU; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 112 "asm.l"
{ yylval.s = lowerdup(yytext); return T_LBL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 113 "asm.l"
{ cstr_t t = substitute(yytext); if(t) { yylval.s = lowerdup(t); BEGIN EXPR; return T_ID; } }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 114 "asm.l"
;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 115 "asm.l"
;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 116 "asm.l"
{ fprintf(stderr, "ERR: %s: invalid character %c @%d!\n", cfn, *yytext, line); doabort(); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 117 "asm.l"
{ BEGIN INITIAL; ++line; return '\n'; }
	YY_BREAK


case 14:
YY_RULE_SETUP
#line 121 "asm.l"
{ yylval.s = lowerdup(yytext); return T_ID; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 122 "asm.l"
{ return ','; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 123 "asm.l"
{ yylval.s = lowerdup(yytext); return T_VAR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "asm.l"
;
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 125 "asm.l"
{ BEGIN MACRO_BODY; ++line; return '\n'; }
	YY_BREAK


case 19:
YY_RULE_SETUP
#line 129 "asm.l"
{ cstr_t t = substitute(yytext); if(t) { yylval.s = lowerdup(t); return T_ID; } }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 130 "asm.l"
{ yylval.s = lowerdup(yytext); return T_VAR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 131 "asm.l"
{ return *yytext; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 132 "asm.l"
{ yylval.i = evalnum(yytext); return T_NUM; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 133 "asm.l"
{ yylval.s = lowerdup(yytext); return T_LBL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 134 "asm.l"
{ return *yytext; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 135 "asm.l"
;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 136 "asm.l"
;
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 137 "asm.l"
{ line += yyleng; return '\n'; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 138 "asm.l"
{ BEGIN CONTENT; return T_ENDMACRO; }
	YY_BREAK


case 29:
YY_RULE_SETUP
#line 142 "asm.l"
{ cstr_t t = substitute(yytext); if(t) { yylval.s = lowerdup(t); return T_ID; } }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 143 "asm.l"
{ return *yytext; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 144 "asm.l"
{ yylval.i = evalnum(yytext); return T_NUM; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 145 "asm.l"
{ yylval.s = lowerdup(yytext); return T_LBL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "asm.l"
{ return *yytext; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 147 "asm.l"
;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 148 "asm.l"
;
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 149 "asm.l"
{ BEGIN INITIAL; ++line; return '\n'; }
	YY_BREAK


case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 153 "asm.l"
{ yytext[yyleng - 1] = '\0'; loadfile(yytext + 1); BEGIN INITIAL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 154 "asm.l"
;
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 155 "asm.l"
{ fprintf(stderr, "ERR: %s: expected quoted filename @%d\n", cfn, line); doabort(); }
	YY_BREAK


case 40:
YY_RULE_SETUP
#line 159 "asm.l"
{ yylval.i = evalnum(yytext); return T_NUM; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 160 "asm.l"
{ yylval.s = lowerdup(yytext); return T_LBL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 161 "asm.l"
{ BEGIN STR; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 162 "asm.l"
{ return *yytext; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 163 "asm.l"
;
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 164 "asm.l"
{ BEGIN INITIAL; ++line; return '\n'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 165 "asm.l"
{ fprintf(stderr, "ERR: %s: invalid character '%c' @%d\n", cfn, *yytext, line); doabort(); }
	YY_BREAK


case 47:
YY_RULE_SETUP
#line 169 "asm.l"
{ yylval.i = *yytext; return T_NUM; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 170 "asm.l"
{ yylval.i = evalnum(yytext); return T_NUM; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 171 "asm.l"
{ BEGIN DB; }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 172 "asm.l"
{ fprintf(stderr, "ERR: %s: unexpected eol @%d!\n", cfn, line); doabort(); }
	YY_BREAK


case 51:
YY_RULE_SETUP
#line 176 "asm.l"
{ id = lowerdup(yytext); BEGIN EQU_REST; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 177 "asm.l"
;
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 178 "asm.l"
{ fprintf(stderr, "ERR: %s: incomplete .equ @%d\n", cfn, line); doabort(); }
	YY_BREAK


case 54:
YY_RULE_SETUP
#line 182 "asm.l"
{ insert(id, lowerdup(yytext)); BEGIN EQU_END; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 183 "asm.l"
;
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 184 "asm.l"
{ fprintf(stderr, "ERR: %s: incomplete .equ @%d\n", cfn, line); doabort(); }
	YY_BREAK


case 57:
YY_RULE_SETUP
#line 188 "asm.l"
{ fprintf(stderr, "ERR: %s: Invalid text after '.equ': '%s' @%d\n", cfn, yytext, line); doabort(); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 189 "asm.l"
;
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 190 "asm.l"
{ BEGIN INITIAL; ++line; }
	YY_BREAK

case 60:
YY_RULE_SETUP
#line 193 "asm.l"
ECHO;
	YY_BREAK
#line 1388 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(CONTENT):
			case YY_STATE_EOF(EQU):
			case YY_STATE_EOF(EQU_REST):
			case YY_STATE_EOF(EQU_END):
			case YY_STATE_EOF(MACRO):
			case YY_STATE_EOF(MACRO_BODY):
			case YY_STATE_EOF(INC):
			case YY_STATE_EOF(DB):
			case YY_STATE_EOF(EXPR):
			case YY_STATE_EOF(STR):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 190 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 190 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 189);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 193 "asm.l"



int yywrap(void)
{
	if(f_i)
	{
		yypop_buffer_state();
		free((void *)cfn);
		fclose(infs[--f_i]);
		line = inls[--l_i];
		cfn  = inns[--n_i];
		return 0;
	}
	else return 1;
}

int main(int argc, char *argv[])
{
	assert(argc>1);
	yyin = fopen(argv[1], "r");
	cfn = strdup(argv[1]);
	yyparse();
	free((void *)cfn);
	fclose(yyin);
	return 0;
}

void loadfile(cstr_t fn)
{
	size_t j;
	for(j = 0 ; j < i_i ; ++j)
	{
		if(strcmp(incs[j], fn) == 0)
		{
			fprintf(stderr, "Warning: Cyclic dependency of '%s'!\n", fn);
		}
	}

	FILE *f = fopen(fn, "r");

	if(!f)
	{
		fprintf(stderr, "ERR: Couldn't open file '%s'!\n", fn);
		doabort();
	}

	incs[i_i++] = strdup(fn);

	infs[f_i++] = f;
	inls[l_i++] = line;
	inns[n_i++] = cfn;
	yypush_buffer_state(yy_create_buffer(f,YY_BUF_SIZE));
	line = 1;
	cfn = strdup(fn);
}

void insert(cstr_t id, cstr_t equ)
{
	cstr_t s = get(id);

	if(s)
	{
		fprintf(stderr, "ERR: Redifinition of '%s': '%s' -> '%s'!\n", id, s, equ);
		doabort();
	}

	ids[i] = id;
	equs[i] = equ;
	++i;
}

char *lowerdup(cstr_t s)
{
	size_t l = strlen(s);
	char *r = malloc(++l);

	while(l--)
	{
		r[l] = MXT_TOLOWER(s[l]);
	}

	return r;
}

void doabort(void)
{
	size_t j;
	for(j = 0 ; j < f_i ; ++j)
	{
		fclose(infs[j]);
	}
	exit(1);
}

int evalnum(cstr_t s)
{
	int v = 0, b = 10;

	if(*s == '0')
	{
		if(!*++s) return 0;

		switch(*s++)
		{
			case 'x':
			case 'X':
				b = 16;
				break;
			case 'b':
			case 'B':
				b = 2;
				break;
			default:
				b = 8;
				break;
		}
	}
	else if(*s == '\'')
	{
		if(*++s == '\\')
		{
			switch(*++s)
			{
				case '0': return '\0';
				case 't': return '\t';
				case 'n': return '\n';
				case 'r': return '\r';
				case '\\': return '\\';
				case '\'': return '\'';
				default: return *s;
			}
		}
		else return *s;
	}

	do
	{
		v = b * v + (*s >= '0' && *s <= '9' ? *s - '0' : MXT_TOLOWER(*s) - 'a');
	} while(*++s);

	return v;
}

cstr_t get(cstr_t id)
{
	size_t j;
	for(j = 0 ; j < i ; ++j)
	{
		if(strcmp(ids[j], id) == 0) return equs[j];
	}

	return NULL;
}

cstr_t substitute(cstr_t id)
{
	cstr_t s = get(id);

	if(!s)
	{
		return id;
	}
	else
	{
		size_t p = strlen(s);
		while(p)
		{
			unput(s[--p]);
		}

		return NULL;
	}
}



